apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-home-review
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/review
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-home
  postBuild:
    substitute:
      ENVIRONMENT: review
