---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  gitops.flux.home/env: base
resources:
  - namespaces/openbao.yaml
  - namespaces/external-secrets.yaml
  - namespaces/infra.yaml
  - namespaces/flux-system.yaml
  - sources/gitrepository.yaml
  - sources/helmrepo-openbao.yaml
  - sources/helmrepo-external-secrets.yaml
  - apps/openbao
  - apps/external-secrets
