---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-home-prod
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-home
  dependsOn:
    - name: infra-home-staging
  postBuild:
    substitute:
      ENVIRONMENT: prod
      GIT_BRANCH: main
      GIT_URL: ssh://git@github.com/infra-home/infra-home.git
