---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
configMapGenerator:
  - name: openbao-values
    namespace: flux-system
    files:
      - values.yaml
resources:
  - helmrelease.yaml
